version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: testpilot-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  backend:
    build: .
    container_name: testpilot-backend
    ports:
      - "8080:5000"
    environment:
      - ENVIRONMENT=production
      - USE_REDIS=true
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    restart: unless-stopped 